# Generated by Django 5.0.6 on 2024-07-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_membership_group_delete_group'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membership',
            table='users_membership',
        ),
    ]
