# Generated by Django 5.0.6 on 2024-07-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_membership_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
