# Generated by Django 5.0.6 on 2024-07-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='transfer',
            table='Transfer',
        ),
        migrations.AlterModelTable(
            name='transferdetail',
            table='TransferDetail',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='Warehouse',
        ),
    ]
