# Generated by Django 5.0.6 on 2024-07-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_table_alter_inventory_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_Father_id',
            new_name='category_father',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='from_warehouse_id',
            new_name='from_warehouse',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='to_warehouse_id',
            new_name='to_warehouse',
        ),
        migrations.RenameField(
            model_name='transferdetail',
            old_name='from_warehouse_id',
            new_name='from_warehouse',
        ),
        migrations.RenameField(
            model_name='transferdetail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='transferdetail',
            old_name='transfer_id',
            new_name='transfer',
        ),
    ]
