# Generated by Django 5.0.6 on 2024-07-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_category_father_id_category_category_father_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferDetail',
            new_name='transfer_detail',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='transfer',
            table='transfer',
        ),
        migrations.AlterModelTable(
            name='transfer_detail',
            table='transfer_detail',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='warehouse',
        ),
    ]
