# Generated by Django 5.0.7 on 2024-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_op',
            name='bill',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='business_talk',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='changes_of_shop',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='complaints',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='connection_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='date',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='discussion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='operation_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='operator_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='operator_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='payed_money',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='process_kind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='reception',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='selling_others',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='selling_paints',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='social_talk',
            field=models.BooleanField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_op',
            name='summary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
