# Generated by Django 5.0.7 on 2024-07-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_op_bill_alter_sales_op_business_talk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_op',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sales_customer'),
        ),
    ]
